// <auto-generated />
namespace BanHangOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class bangtacgiaNhaxuatbanNoteCustomerNoteOrderlan2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bangtacgiaNhaxuatbanNoteCustomerNoteOrderlan2));
        
        string IMigrationMetadata.Id
        {
            get { return "202212241020310_bangtacgiaNhaxuatbanNoteCustomerNoteOrderlan2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
